### PR TITLE
Added preferences

### PR DESCRIPTION
**Pull request by ghost**
I love the tweak, so I added some preferences for it. Right now, it's just a kill switch and a scream selector, but you can only select between two screams. Hopefully I'll figure out how to add more screams (I'll probably take a look at Cylinder's code for that). Sorry if my code is shit, I'm learning, but it at least works.

### CODE REVIEW

**Comment by srolfe** [comment]
I absolutely LOVE that you chose to do this, but I actually had the code for this almost done last night. Just merged it in. It allows for custom sounds as well.

So, unfortunately, I won't be merging this.

**Comment by ghost** [comment]
Thanks! It was fun to work on! If you don't do it in the near future, then I'll try to add support for any wav file that is put in the resources directory.—
Milo Darling

**Comment by srolfe** [comment]
That's supported already.

The resources directory is copied to /Library/FreeFall and the preference pane loads all files (not just wav) from that directory for choosing the sound to use. So, placing a sound in there allows you to use it with the tweak.

I just need to play the clip when they're selected now, so you don't need to drop the device to hear it first, but that shouldn't be too hard to hook the set: methods.

**Comment by ghost** [comment]
I did that in my fork, so feel free to look at that.—
Milo Darling

**Pull request closed without merging**
